const { MessageEmbed } = require('discord.js');
module.exports = {
        name: 'help',
        description: 'command list',
	execute(message, args) {

                if (!args[0]) {

                        const Embed = new MessageEmbed()
                        .setTitle('Command List')
                        .setColor(0xbbffff)
                        .setThumbnail("https://i.imgur.com/WWM4K98.png")
                        .setDescription("Use `!help <command name>` for more information")
                        .addField("<:SSTier:869316489931546644> Card Game", "`!pull` `!info` `!infomy` `!search` `!anime` `!shop`\n`!sell` `!buy` `!trade` `!profile` `!level` `!daily`\n`!fav` `!give` `!gift` `!inventory` `!top` `!stats`\n`!balance` `!list` `!pity` `!find` `!rank` `!lvlup`\n`!shards` `!refine` `!dungeon` `!abilities`")
                        .addField("🎭 Gambling", "`!recommend` `!random` `!flip` `!flipping` `!name`")
                        .addField("<:math:874446676008501248> Math", "`!math` `!fib` `!gcd` `!lcm`")
                        .addField("🎐 Other", "`!camelot` `!avatar` `!ping` `!emojilist` `!purge`\n`!ram` `!colorpicker` `!userstats`")
                        .setFooter("Camelot V2.2.3 • Made by Apollo24 & PokeLink", "https://i.imgur.com/syj1LqO.jpeg")
                        message.channel.send(Embed);

                } else {

                        const Embed = new MessageEmbed()
                        .setTitle('Help')
                        .setColor(0xbbffff)
                        .setThumbnail("https://i.imgur.com/WWM4K98.png")
                        .setDescription("Use `!help <command name>` for more information")
                        .setFooter("Camelot V2.2.3 • Made by Apollo24 & PokeLink", "https://i.imgur.com/syj1LqO.jpeg")

                        let help = args[0].toLowerCase();
                        switch (help) {
                                case "abilities" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "anime" : Embed.setDescription("**Usage**: `!anime`\n**Alias**: `!anime`, `!a`\n\nAll franchises included in the card game will be listet alphabetically. The ones you have completed will be marked.").setTitle("Help !anime"); break;
                                case "a" : Embed.setDescription("**Usage**: `!anime`\n**Alias**: `!anime`, `!a`\n\nAll franchises included in the card game will be listet alphabetically. The ones you have completed will be marked.").setTitle("Help !anime"); break;
                                case "avatar" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "balance" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "buy" : Embed.setDescription("**Usage**: `!buy <character pack ID>`\n**Alias**: `!buy`\n\nBuy a character pack. See `!shop` for a list of packs available. There is no limit to the amount of packs you can buy but please note that <:SSTier:869316489931546644> **Tier** characters are excluded from **Morpheus Blessing** (character pack #6).").setTitle("Help !buy"); break;
                                case "camelot" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "colorpicker" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "daily" : Embed.setDescription("**Usage**: `!daily`\n**Alias**: `!daily`\n\nYou can claim your daily coins once per day. The cooldown will be reset at **midnight**. The amount you get is proportional to your level, you start off with **200**<:coins:872926669055356939> and get an extre **10**<:coins:872926669055356939> for every other level you reach.\n**Example**: If your current level is 12 you get a total of **260**<:coins:872926669055356939> (200 + (12/2)\*10)").setTitle("Help !daily"); break;
                                case "dungeon" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "d" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "emojilist" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "favourite" : Embed.setDescription("**Usage**: `!favourite <character name or ID>`\n**Alias**: `!favourite`, `!favorite`, `!fav`\n\nSelect your favourite character. You have to own it to be able to select it. The image of that character will then be displayed as a thumbnail on various commands of yours like on your `!profile` or `!level`.").setTitle("Help !favourite"); break;
                                case "favorite" : Embed.setDescription("**Usage**: `!favourite <character name or ID>`\n**Alias**: `!favourite`, `!favorite`, `!fav`\n\nSelect your favourite character. You have to own it to be able to select it. The image of that character will then be displayed as a thumbnail on various commands of yours like on your `!profile` or `!level`.").setTitle("Help !favourite"); break;
                                case "fav" : Embed.setDescription("**Usage**: `!favourite <character name or ID>`\n**Alias**: `!favourite`, `!favorite`, `!fav`\n\nSelect your favourite character. You have to own it to be able to select it. The image of that character will then be displayed as a thumbnail on various commands of yours like on your `!profile` or `!level`.").setTitle("Help !favourite"); break;
                                case "fib" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "find" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "flip" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "flipping" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "give" : Embed.setDescription("**Usage**: `!give @user <amount of coins>`\n**Alias**: `!give`\n\nSend coins to another user. There is no limit. Please be aware that using alt accounts to get an advantage over other players is forbidden and can result in an inventory reset or even an account ban from Camelot.").setTitle("Help !give"); break;
                                case "gift" : Embed.setDescription("**Usage**: `!gift @user <character name or ID>`\n**Alias**: `!gift`\n\nSend characters to another user. Use the characters full **name** or **ID**. Please be aware that using alt accounts to get an advantage over other players is forbidden and can result in an inventory reset or even an account ban from Camelot.").setTitle("Help !gift"); break;
                                case "info" : Embed.setDescription("**Usage**: `!info <character name or ID>`\n**Alias**: `!info`, `!i`\n\nSearch for a character that's in the game. You don't have to use the characters full name as long as there's no other match fitting your input. The characters full **name**, **rarity**, **ID** and the **franchise** it is from will be displayed.\nUse `!infomy` if you want to look for a character you already have.").setTitle("Help !info"); break;
                                case "i" : Embed.setDescription("**Usage**: `!info <character name or ID>`\n**Alias**: `!info`, `!i`\n\nSearch for a character that's in the game. You don't have to use the characters full name as long as there's no other match fitting your input. The characters full **name**, **rarity**, **ID** and the **franchise** it is from will be displayed.\nUse `!infomy` if you want to look for a character you already have.").setTitle("Help !info"); break;
                                case "infomy" : Embed.setDescription("**Usage**: `!infomy <character name or ID>`\n**Alias**: `!infomy`, `!imy`, `!im`\n\nSearch for a character you already have in your inventory. You don't have to use the characters full name as long as there's no other match fitting your input. The characters full **name**, **rarity**, the **franchise** it is from, how many **copies** you possess and it's **\*refinement** will be displayed.\nUse `!info` if you want to look for a character you don't have.").setTitle("Help !infomy").addField("\*Refinement (<:refinement:869132309125824552>)", "You can level up a characters refinement by collecting more than 1 copy of a character. There is no other advantage in doing so as of now."); break;
                                case "imy" : Embed.setDescription("**Usage**: `!infomy <character name or ID>`\n**Alias**: `!infomy`, `!imy`, `!im`\n\nSearch for a character you already have in your inventory. You don't have to use the characters full name as long as there's no other match fitting your input. The characters full **name**, **rarity**, the **franchise** it is from, how many **copies** you possess and it's **\*refinement** will be displayed.\nUse `!info` if you want to look for a character you don't have.").setTitle("Help !infomy").addField("\*Refinement (<:refinement:869132309125824552>)", "You can level up a characters refinement by collecting more than 1 copy of a character. There is no other advantage in doing so as of now."); break;
                                case "im" : Embed.setDescription("**Usage**: `!infomy <character name or ID>`\n**Alias**: `!infomy`, `!imy`, `!im`\n\nSearch for a character you already have in your inventory. You don't have to use the characters full name as long as there's no other match fitting your input. The characters full **name**, **rarity**, the **franchise** it is from, how many **copies** you possess and it's **\*refinement** will be displayed.\nUse `!info` if you want to look for a character you don't have.").setTitle("Help !infomy").addField("\*Refinement (<:refinement:869132309125824552>)", "You can level up a characters refinement by collecting more than 1 copy of a character. There is no other advantage in doing so as of now."); break;
                                case "inventory" : Embed.setDescription("**Usage**: `!inventory <page number (optional)> <@user (optional)>`\n**Alias**: `!inventory`, `!inv`, `!invr`, `!inva`\n\nSee yours or someone else's inventory. It will be sorted after your pull order by default. Use `!invr` if you want to sort it after rarity and `!inva` to sort it alphabetically.").setTitle("Help !inventory"); break;
                                case "inv" : Embed.setDescription("**Usage**: `!inventory <page number (optional)> <@user (optional)>`\n**Alias**: `!inventory`, `!inv`, `!invr`, `!inva`\n\nSee yours or someone else's inventory. It will be sorted after your pull order by default. Use `!invr` if you want to sort it after rarity and `!inva` to sort it alphabetically.").setTitle("Help !inventory"); break;
                                case "inva" : Embed.setDescription("**Usage**: `!inventory <page number (optional)> <@user (optional)>`\n**Alias**: `!inventory`, `!inv`, `!invr`, `!inva`\n\nSee yours or someone else's inventory. It will be sorted after your pull order by default. Use `!invr` if you want to sort it after rarity and `!inva` to sort it alphabetically.").setTitle("Help !inventory"); break;
                                case "invr" : Embed.setDescription("**Usage**: `!inventory <page number (optional)> <@user (optional)>`\n**Alias**: `!inventory`, `!inv`, `!invr`, `!inva`\n\nSee yours or someone else's inventory. It will be sorted after your pull order by default. Use `!invr` if you want to sort it after rarity and `!inva` to sort it alphabetically.").setTitle("Help !inventory"); break;
                                case "level" : Embed.setDescription("**Usage**: `!level <@user (optional)>`\n**Alias**: `!level`, `!lvl`\n\nSee your current level, how much more XP you need to level up and a progress bar. The progress bar is divided into 8. Currently the only way of getting XP is by pulling characters. You get **1-10** XP for each pull. If you've pulled an <:STier:869316518675095552> Tier character that number will be multiplied by **2**, and if you've pulled an <:SSTier:869316489931546644> Tier you get an extra **20** XP on top of what you would've gotten.").setTitle("Help !level"); break;
                                case "levelup" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "list" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "lu" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "lvl" : Embed.setDescription("**Usage**: `!level <@user (optional)>`\n**Alias**: `!level`, `!lvl`\n\nSee your current level, how much more XP you need to level up and a progress bar. The progress bar is divided into 8. Currently the only way of getting XP is by pulling characters. You get **1-10** XP for each pull. If you've pulled an <:STier:869316518675095552> Tier character that number will be multiplied by **2**, and if you've pulled an <:SSTier:869316489931546644> Tier you get an extra **20** XP on top of what you would've gotten.").setTitle("Help !level"); break;
                                case "lvlup" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "math" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "name" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "ping" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "pity" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "profile" : Embed.setDescription("**Usage**: `!profile <@user (optional)>`\n**Alias**: `!profile`, `!pr`\n\nGet yours or someone else's card game profile. Your current `!level`, amount of coins and progress will be shown.").setTitle("Help !profile"); break;
                                case "pr" : Embed.setDescription("**Usage**: `!profile <@user (optional)>`\n**Alias**: `!profile`, `!pr`\n\nGet yours or someone else's card game profile. Your current `!level`, amount of coins and progress will be shown.").setTitle("Help !profile"); break;
                                case "pull" : Embed.setDescription("**Usage**: `!pull`\n**Alias**: `!pull`, `!p`\n\nPull a character. You can use this command 4 times every 2 hours. You get an extra pull for reaching `!level` **10** and **20** each, raising the total to 6 pulls every 2 hours.").setTitle("Help !pull").addFields({ name: 'Droprates', value: "<:SSTier:869316489931546644> **Tier**: 0,3%\n<:ATier:869316558013464627> **Tier**: 4,2%\n<:CTier:869316602858991657> **Tier**: 25,3%", inline: true },{ name: '_ _', value: "<:STier:869316518675095552> **Tier**: 1,8%\n<:BTier:869316586803179571> **Tier**: 12,6%\n<:DTier:869316616071032843> **Tier**: 55,8%", inline: true },); break;
                                case "p" : Embed.setDescription("**Usage**: `!pull`\n**Alias**: `!pull`, `!p`\n\nPull a character. You can use this command 4 times every 2 hours. You get an extra pull for reaching `!level` **10** and **20** each, raising the total to 6 pulls every 2 hours.").setTitle("Help !pull").addFields({ name: 'Droprates', value: "<:SSTier:869316489931546644> **Tier**: 0,3%\n<:ATier:869316558013464627> **Tier**: 4,2%\n<:CTier:869316602858991657> **Tier**: 25,3%", inline: true },{ name: '_ _', value: "<:STier:869316518675095552> **Tier**: 1,8%\n<:BTier:869316586803179571> **Tier**: 12,6%\n<:DTier:869316616071032843> **Tier**: 55,8%", inline: true },); break;
                                case "purge" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "ram" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "random" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "rank" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "rankmy" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "ranks" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "ref" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "refine" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "recommend" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "search" : Embed.setDescription("**Usage**: `!search <anime name or alias>`\n**Alias**: `!search`, `!s`\n\nSearch for an anime using it's full **name** or **alias**. The characters will be listed according to their rarity, then ID. Your progress is shown next to the name, and characters you own will be marked.").setTitle("Help !search"); break;
                                case "s" : Embed.setDescription("**Usage**: `!search <anime name or alias>`\n**Alias**: `!search`, `!s`\n\nSearch for an anime using it's full **name** or **alias**. The characters will be listed according to their rarity, then ID. Your progress is shown next to the name, and characters you own will be marked.").setTitle("Help !search"); break;
                                case "sell" : Embed.setDescription("**Usage**: `!sell <name or ID>`\n**Alias**: `!sell`\n\nSell your characters. You can't get them back once you've confirmed the action. The amount of coins you get are as listed below. Also, you can use `!sell last` to sell your latest pulled character.").setTitle("Help !sell").addFields({ name: 'Values', value: "<:SSTier:869316489931546644> **Tier**: 5000<:coins:872926669055356939>\n<:ATier:869316558013464627> **Tier**: 500<:coins:872926669055356939>\n<:CTier:869316602858991657> **Tier**: 100<:coins:872926669055356939>", inline: true },{ name: '_ _', value: "<:STier:869316518675095552> **Tier**: 1000<:coins:872926669055356939>\n<:BTier:869316586803179571> **Tier**: 250<:coins:872926669055356939>\n<:DTier:869316616071032843> **Tier**: 50<:coins:872926669055356939>", inline: true },); break;
                                case "shards" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                case "shop" : Embed.setDescription("**Usage**: `!shop`\n**Alias**: `!shop`\n\nSee the card game shop. There are different types of character packs listed with short descriptions and their ID's. Use `!buy <id>` to buy one. There is no limit to the amount of packs you can buy, except if it is statet so in it's description.").setTitle("Help !shop"); break;
                                case "stats" : Embed.setDescription("**Usage**: `!stats`\n**Alias**: `!stats`\n\nSee some stats of Camelots card game, specifically the amount of characters in a Tier, how many male and female characters there are as well as the amount of franchises included in Camelot.").setTitle("Help !stats"); break;
                                case "top" : Embed.setDescription("**Usage**: `!top`\n**Alias**: `!top`\n\nGet your servers toplist. It is ranked after user levels. The thumbnail will either be a random character of the first placed user or their favourite character if they have one.").setTitle("Help !top"); break;
                                case "trade" : Embed.setDescription("**Usage**: `!trade @user <char to offer> , <char to receive>`\n**Alias**: `!trade`\n\nTrade your characters with someone else. Use the characters full **name** or **ID**. The other person will have **15** seconds to accept the offer or it will be cancelled.").setTitle("Help !trade"); break;
                                case "userstats" : Embed.setDescription("There hasn't been added any informations to this command yet. Try it out for yourself.").setTitle("Help !"+help); break;
                                default : Embed.setDescription(`There is currently no such command as **${help}**`).setTitle("Help"); break;
                        };
                        message.channel.send(Embed);
                };
                
	},
};